// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTIOUEr6X5DGm4G-0Il689dJW9W_D8b4',
    appId: '1:1046735195384:web:686ca6a4d094e71b44ff0d',
    messagingSenderId: '1046735195384',
    projectId: 'authentication-app-22547',
    authDomain: 'authentication-app-22547.firebaseapp.com',
    storageBucket: 'authentication-app-22547.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUKWqUroUBNHHA5O3KRjWhJoHbvbl4cA',
    appId: '1:1046735195384:android:789242825262fb1144ff0d',
    messagingSenderId: '1046735195384',
    projectId: 'authentication-app-22547',
    storageBucket: 'authentication-app-22547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rTY8w30XniJOFA3DB0kkJkOcUl2GWuM',
    appId: '1:1046735195384:ios:d469311bfbdd6e0b44ff0d',
    messagingSenderId: '1046735195384',
    projectId: 'authentication-app-22547',
    storageBucket: 'authentication-app-22547.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rTY8w30XniJOFA3DB0kkJkOcUl2GWuM',
    appId: '1:1046735195384:ios:d469311bfbdd6e0b44ff0d',
    messagingSenderId: '1046735195384',
    projectId: 'authentication-app-22547',
    storageBucket: 'authentication-app-22547.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATTIOUEr6X5DGm4G-0Il689dJW9W_D8b4',
    appId: '1:1046735195384:web:60ed895c2c509bea44ff0d',
    messagingSenderId: '1046735195384',
    projectId: 'authentication-app-22547',
    authDomain: 'authentication-app-22547.firebaseapp.com',
    storageBucket: 'authentication-app-22547.firebasestorage.app',
  );
}
